# Generated by Django 3.1.2 on 2022-07-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drives',
            name='image',
            field=models.FileField(default='none', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drives',
            name='image_data',
            field=models.BinaryField(null=True),
        ),
    ]
