# Generated by Django 3.1.2 on 2021-01-08 05:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0004_remove_person_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='licensed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='test',
            name='personnel',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), null=True, size=None),
        ),
    ]
