# Generated by Django 3.1.2 on 2021-01-08 05:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0005_auto_20210107_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='personnel',
        ),
        migrations.AddField(
            model_name='test',
            name='people',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), null=True, size=None),
        ),
    ]
